### ISSUE TITLE
함수 완성하기(추가되는 영역)

### ISSUE THREAD

**Issue by wjs4199** [wjs4199/2020OSS_teams#2]
search 함수 2개 추가했습니다!

**Comment by wjs4199** [comment]
원격저장소를 제걸로 옮겼어요!

**Comment by wjs4199** [comment]
searchstar 함수랑 searchfunction 함수 만들었습니다!

**Comment by Yejin-Yeon** [comment]
main.c menu2,3,4 추가하고 READ파일 업데이트했습니다~!

**Comment by wjs4199** [comment]
merge 했씁니다!

**Comment by wjs4199** [comment]
manager.c에서 seachname함수 조금 수정했습니다!

**Comment by Yejin-Yeon** [comment]
book.h 조금 수정했습니다 pr 부탁드려용~!

**Comment by wjs4199** [comment]
merge했습니다!
