### ISSUE TITLE
프로젝트 마무리

### ISSUE THREAD

**Issue by wjs4199** [wjs4199/2020OSS_teams#6]
프로젝트 마무리 단계입니다!

**Comment by Yejin-Yeon** [comment]
screenshots menu 1,2,3,4,5 올렸습니당!

**Comment by Yejin-Yeon** [comment]
screenshots menu 6,0 올렸습니당!

**Comment by wjs4199** [comment]
md조금 수정하고, main.c 주석 수정했습니다!

**Comment by wjs4199** [comment]
manager.c 함수 수정했습니다!

**Comment by Yejin-Yeon** [comment]
readme 업데이트했습니다~!

**Comment by Yejin-Yeon** [comment]
wiki 업데이트 완료했습니다! 프로젝트 정말 수고하셨습니당:)!!!ㅎㅎ

**Comment by wjs4199** [comment]
수고하셨습니당!!ㅎㅎ:)
